Add max_plane_float_override config variable
ome/omero-model pull request #81
Opened 2022-05-25 14:36 UTC by kkoz

Fixes ome/omero-romio#36
Add a config variable which can be used to alter the logic concerning `requiresPixelsPyramid` for floating point data types.

2022-05-25 15:46 UTC, sbesson commented on src/main/resources/omero-model.properties
> +# If true, server will not require pyramids (or generate them)
One issue with this statement is that it might mislead administrators in thinking that setting this value to `false` will allow the server to generate pyramids for floating point pixel types. 
As per https://github.com/ome/omero-romio/pull/37/files#diff-3fa8f8c0d7379102b6f4db9131d2403a262eaa43645c2bc98b85455e3f5947cfR302-R307, I understand the pyramid generation is still (rightfully &) unconditionally disabled for floating-point pixel types

2022-05-26 10:21 UTC, pwalczysko commented
Tested on merge-ci:

1. With this PR, with the ``omero config set omero.pixeldata.max_plane_float_override`` unset. Verified that the test in Line 5 of https://docs.google.com/spreadsheets/d/1FD_oS8zQxOM1YOscMX6Xm-VxgcD-w9xBr7VECmNEQsw/edit?usp=sharing is causing the server to be unresponsive. 
2. With this PR, set the ``omero config set omero.pixeldata.max_plane_float_override true`` in https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-server/configure and rerun the build
3. After this, the test in Line 5 started to show no detrimental effects to the server. The speed of opening of the images was fine, as well as switching channels on and off.

2022-05-26 10:22 UTC, pwalczysko commented
@kkoz @chris-allan I think we need a short discussion after @sbesson is back, but based on the test in https://github.com/ome/omero-model/pull/81#issuecomment-1138383105 LGTM

2022-05-26 10:22 UTC, pwalczysko approved these changes

2022-05-26 14:06 UTC, sbesson commented
> Note the interesting behaviour of https://merge-ci.openmicroscopy.org/web/webclient/?show=image-231865 when the config property is set to false. It does not have any Preview shown and does not open in iviewer. Thumbnail is present. When the property is set to true, this image does load in Preview and iviewer, but because no pyramids are present, the zooming is not smooth.


This matches my understanding of the primary limitation of setting `omero.pixeldata.max_plane_float_override` to  `false` i.e.
- floating-point data is subjected to the same plane size based pyramidal requirement as other types
- the OMERO.server pyramid generation is still disabled for floating-point data

Concretely
- if you are working with large pyramidal floating-point images, everything should work as expected  and I believe that's what your testing demonstrates
- if you are working with large floating-point images without pyramids, the data will import but effectively becomes unusable for the clients. This should be identical to the current behavior where `PixelData-0` is disabled on a server and large images without pyramids are imported

2022-05-26 14:53 UTC, chris-allan commented
@sbesson: That's exactly correct.

2022-05-26 15:15 UTC, sbesson commented on src/main/resources/omero-model.properties
> +omero.pixeldata.max_plane_float_override=true
While getting my head around the property wording, I realised a more advanced approach would be to construct this property as a list of pixel types ignored for the pyramid requirement e.g.

```
omero.pixeldata.ignored_types=float,double
```

The main advantage of this approach is a better configurability e.g. a server could choose to only ignore `double` for the pyramid requirement for instance.

For full disclosure, I am not aware of a use case where the scenario described above would be mandatory. If no one thinks of one, the approach taken here i.e. a simple boolean is probably the easiest to configure and we can safely ignore this digression ;) I just wanted to capture the alternative in case it might be useful.

2022-05-26 15:18 UTC, chris-allan commented on src/main/resources/omero-model.properties
> +omero.pixeldata.max_plane_float_override=true
I have no problem switching to this style and it's certainly more configurable. We'd just have to work out some potentially gnarly Spring configuration.

2022-05-26 15:25 UTC, chris-allan commented on src/main/resources/omero-model.properties
> +omero.pixeldata.max_plane_float_override=true
(That being said, given IMHO how problematic the decision to have this exception has turned out I am disinclined to make it the problem worse in the future by adding more chances for weird exceptions)

2022-05-26 15:30 UTC, sbesson commented
While reviewing https://omero.readthedocs.io/en/latest/sysadmins/config.html#pixeldata, I also realised the definition of the `max_plane_height` `max_plane_width` will need to be updated to reflect this new property. I suspect this will require a bigger rewrite as the current definition conflates the concepts of pyramid requirement and pyramid generation. So I'd propose this to happen in a follow-up PR

2022-05-26 16:13 UTC, sbesson requested changes
@chris-allan teasingly reminded me of [#5426](https://github.com/ome/openmicroscopy/pull/5426) and my responsibility in the confusion of the `max_plane*` property description :smile:

@kkoz could you take trya and update these descriptions to the best of your understanding and also include a reference to the new introduced property for the pyramid requirement?

We should make sure that the configuratoin glossary of the OMERO documentation is properly regenerated for the upcoming OMERO.server release

2022-05-26 16:21 UTC, sbesson commented on src/main/resources/omero-model.properties
> +omero.pixeldata.max_plane_float_override=true
Fair enough. As said above, unless this is motivated by a real use case, I think the current property is simpler to configure and covers immediate needs.

2022-05-26 20:10 UTC, jburel commented
Configuration should be generated by https://github.com/ome/omero-documentation/blob/develop/.github/workflows/update.yml

2022-05-30 14:26 UTC, sbesson approved these changes
Thanks @kkoz, this should allow the server configuration glossary of the reference documentation to be updated accordingly. I'll use the occasion to review the references to the pyramid generation and correct where needed.

2022-05-30 14:26 UTC, merged